apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-snake
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 256Mi
            cpu: "250m"
          requests:
            memory: 128Mi
            cpu: "80m"
